# Generated by Django 3.2.4 on 2021-10-26 20:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetCenterline',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('objectid', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fnode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('tnode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('lpoly', models.CharField(max_length=1)),
                ('rpoly', models.CharField(max_length=1)),
                ('length', models.DecimalField(decimal_places=15, max_digits=24)),
                ('stc12', models.CharField(max_length=1)),
                ('stcl2_id', models.CharField(max_length=1)),
                ('pre_dir', models.CharField(max_length=2)),
                ('st_name', models.CharField(max_length=28)),
                ('st_type', models.CharField(max_length=4)),
                ('suf_dir', models.CharField(max_length=5)),
                ('zip_left', models.DecimalField(decimal_places=0, max_digits=5)),
                ('zip_right', models.DecimalField(decimal_places=0, max_digits=5)),
                ('l_f_add', models.DecimalField(decimal_places=0, max_digits=5)),
                ('l_t_add', models.DecimalField(decimal_places=0, max_digits=5)),
                ('r_f_add', models.DecimalField(decimal_places=0, max_digits=5)),
                ('r_t_add', models.DecimalField(decimal_places=0, max_digits=5)),
                ('st_code', models.DecimalField(decimal_places=0, max_digits=5)),
                ('l_hundred', models.DecimalField(decimal_places=0, max_digits=5)),
                ('r_hundred', models.DecimalField(decimal_places=0, max_digits=5)),
                ('seg_id', models.DecimalField(decimal_places=0, max_digits=7)),
                ('oneway', models.CharField(max_length=2)),
                ('class_field', models.DecimalField(decimal_places=0, max_digits=2)),
                ('responsibl', models.CharField(max_length=14)),
                ('update', models.DateField()),
                ('newsegdate', models.DateField()),
                ('multi_rep', models.DecimalField(decimal_places=0, max_digits=1)),
                ('streetlabe', models.CharField(max_length=32)),
                ('stname', models.CharField(max_length=32)),
                ('shape_len', models.DecimalField(decimal_places=15, max_digits=24)),
            ],
        ),
    ]
