#!/bin/bash

set -e

if [[ -n "${PROJECT_NAME_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
    if [[ "${1:-}" = "--help" ]]; then
        usage
    else
        # Execute Django test suite
        ./scripts/manage test
    fi
fi
